#!/bin/sh
set -e

ua_inst () {
	update-alternatives \
        --install /etc/X11/xinit/xinput.d/$1 xinput-$1 \
        /etc/X11/xinit/xinput.d/$2 $3 ;
}

case "$1" in
    configure)
        # Set up default
        ua_inst all_ALL default  10
        ua_inst all_ALL none  0
        # Set up *-xim
        ua_inst th_TH th-xim  20
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
