#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        update-alternatives --remove xinput-ja_JP /etc/X11/xinit/xinput.d/none
        update-alternatives --remove xinput-th_TH /etc/X11/xinit/xinput.d/th-xim
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
